# The proposal
<!--
This is where the proposal should be outlined. 
-->

## Overview

In response to a growing demand for accessible and comprehensive educational resources in causal inference within the R community, we propose the development of a Causal Inference In a Box course. Leveraging a "teach the teacher" model and building on the successful Data Science in a Box template, we will provide instructional materials, including slide decks, lab exercises, and assessments, all meticulously designed to facilitate effective learning. Additionally, we are committed to ensuring inclusivity by offering alternative formats for diverse learning preferences. This comprehensive course, supported by dedicated pedagogical software tools, will revolutionize how practitioners approach causal inference in the R environment, ultimately enhancing the quality and reliability of their research and analyses.

## Detail

### Software Development

We will develop software with a distinct pedagogical focus, designed expressly to facilitate compelling learning experiences. This user-friendly software will be crafted to guide learners through the intricacies of causal design and inference within the R environment. We actively develop and maintain several of the tools which will complement and integrate with Causal Inference in a Box:  [ggdag](https://github.com/r-causal/ggdag): a package to facilitate creating causal diagrams, [halfmoon](https://github.com/r-causal/halfmoon): a package to assist with checking and visualizing balance between exposure groups, [propensity](https://github.com/r-causal/propensity): a package for fitting propensity score models, and many others. As part of the Causal Inference in a Box ecosystem, this proposal supports the development of pedagogical extensions to ggdag and propensity to release to CRAN. ggdag will be extended to easily use best practices in DAG development and display that have emerged over the past few years; these extensions are more robust and easier to understand, in line with our teaching philosophy. propensity will continue to expand its set of tools for working with propensity scores in a way that is principled, accurate, and easy to teach.

### Curriculum Development

The content of Causal Inference in a Box will follow the structure of our forthcoming book, [*Causal Inference in R*](https://www.r-causal.org/), which is publicly available at [r-causal.org](https://www.r-causal.org/). We will create slide decks, lab exercises, and assessments, all hosted on GitHub. The content will include references to relevant book sections, allowing learners to easily navigate between the course and the book for a deeper understanding. We plan to create the content in plain language, avoiding jargon or technical terms that may be unfamiliar to learners.

**Slide Decks:** We will create visually engaging slide decks for each chapter. These will incorporate clear explanations, illustrative examples, and relevant visuals to facilitate understanding.

**Lab Exercises:** We will develop a series of hands-on lab exercises corresponding to the concepts covered in each chapter. Additionally, we will provide datasets, code templates, and specific tasks to guide learners through applying causal inference techniques in R.

**Assessments:** We will integrate quizzes, self-assessment questions, and knowledge checks within the course materials to reinforce learning and allow educators and learners to gauge progress. Some assessments will be interactive, such as using learnr modules to facilitate active learning.
We are experienced teachers versed in the science of learning, particularly for teaching code and analysis; all components of our course will follow best practices for cultivating understanding, such as those presented in [Teaching Tech Together](https://teachtogether.tech/) and [How Learning Happens](https://www.amazon.com/gp/product/0367184575/).

### Accessibility and Inclusivity

We plan to provide alternative formats for learners with different learning preferences, such as text descriptions of visualizations for the visually impaired. Causal Inference in a Box also provides a new learning avenue for those who wish to refrain from engaging with the deep mathematical underpinnings of causal inference, as many textbooks and learning resources currently feature. As an alternative, we wish to eliminate jargon and theoretical edge cases in favor of a rapid on-ramp to apply valid causal inference with R.
