# Project plan

## Start-up phase

The timeline for this project is January 01, 2024, to December 21, 2024.

We will create a repository on the r-causal GitHub organization for Causal Inference in a Box under the Creative Commons Attribution-ShareAlike 4.0 International Public License. All relevant software repositories already exist under the MIT license in the r-causal GitHub organization.

Additionally, we will create a publicly available Posit Cloud space via a git import, allowing us to regularly sync material from the repository to the ready-to-use Cloud space.

## Community communication

We will announce the project on our [r-causal blog](https://r-causal.github.io/r-causal-blog/), and social media and provide regular updates throughout the progress. As teachers already use many of our materials, we expect community feedback via GitHub and other communication. When the project is complete, we will make a blog post acknowledging all community contributors. We will also submit talks to conferences such as useR! and posit::conf() for both 2024 and 2025. Additionally, we will provide the R Consortium with regular reports.

## Technical delivery

Our deliverables are as follows:: 

* A GitHub repository containing all slides, labs, and assessments for the Causal Inference in a Box course.
* A deployed GitHub Pages website for the repository containing relevant rendered materials, such as HTML slides.
* A deployed Posit Cloud learning space with all materials and packages ready to use.
* A 0.1.0 CRAN release for propensity and a 1.0.0 CRAN release for ggdag.
